# Generated by Django 4.0.4 on 2022-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
